# Site settings
title: Geek Harvest
email: geekharvest@fireflylogic.com
url: https://geekharvest.github.io
description: "Geek Harvest is a summer activity for programming user groups in which parents in the group, bring their kids to some meetings, pick a summer coding project, and show-and-tell that work at the group's September meeting."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Geek Harvest
  location: Snail Mail
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/geekharvest
  - title: github
    url: http://github.com/geekharvest

# Postal address (add as many lines as necessary)
address:
  - line: 1000 Main Street #201
  - line: Nashville, TN 37206

# Credits content
credits: 'The idea and initial leg-work for Geek Harvest was by Bryan Hunter of <a href="http://fireflylogic.com">Firefly Logic</a><br/><br/>This site''s lovely, opensource theme (Freelancer) was created by <a href="http://startbootstrap.com">Start Bootstrap</a>'

# Build settings
markdown: kramdown
permalink: pretty
